/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const dynamic _kFontPkg = null;

  static const IconData cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offers = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders_history = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_policy = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData read_notification = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData returns_and_exchange = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unread_notification = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
